// Track list from user's manual inspection of MP3 metadata
// Format: { trackNumber: "artist - songName - album" }

const trackList = {
  1: "Ada Juarez - (Drum Cover) Jumpsuit - twenty one pilots",
  2: "Green Day - American Idiot - American Idiot",
  3: "Korn - Blind - Life Is Peachy",
  4: "Deftones - Bored - Around the Fur",
  5: "Fruko y Sus Tesos - Cachondea",
  6: "Mangu - Calle Luna Calle Sol",
  7: "Aaron Spears - Caught Up",
  8: "Slipknot - Duality - Vol. 3: The Subliminal Verses",
  9: "C+C Music Factory - Gonna Make You Sweat (Everybody Dance Now) - Gonna Make You Sweat",
  10: "C5 - Hoy Te Vas",
  11: "Willie Colón - Idilio",
  12: "J Álvarez - Junto El Amanecer",
  13: "Papa Roach - Last Resort - Infest",
  14: "La Familia Andina - Marcela",
  15: "Jerry Rivera - Mi Libertad",
  16: "B.o.B - Nothin' On You - B.o.B Presents: The Adventures of Bobby Ray",
  17: "Puya - Oasis - Fundamental",
  18: "Joe Arroyo - Pa' L Bailador - La Verdad",
  19: "Rage Against the Machine - People of the Sun - Evil Empire",
  20: "Skrillex - Rock n Roll - Scary Monsters and Nice Sprites",
  21: "BranBeezy - She Wiggin'",
  22: "Slipknot - The Blister Exists - Vol. 3: The Subliminal Verses",
  23: "La Familia Andina - Amor Amor - Viejitas Pero Buenas Disc 1",
  24: "Skrillex - Bangarang - Bangarang",
  25: "Deftones - Digital Bath - White Pony",
  26: "Héctor Lavoe - Juanito Alimaña - Vigilante",
  27: "Rage Against the Machine - Killing in the Name - Rage Against the Machine",
  28: "C5 - No Te Vuelvas a Caer",
  29: "Slipknot - People = Shit - Iowa",
  30: "Skrillex - Scary Monsters and Nice Sprites - Scary Monsters and Nice Sprites",
  31: "Slipknot - Sic - Slipknot",
  32: "Blur - Song 2 - The Best of Blur Disc 1",
  33: "Marilyn Manson - The Beautiful People - Antichrist Superstar",
  34: "AB Logic - The Hitman - AB Logic",
  35: "Maroon 5 - This Love - Songs About Jane",
  36: "Slipknot - Three Nil - Vol. 3: The Subliminal Verses",
  37: "David Guetta - When Love Takes Over - When Love Takes Over",
  38: "The Killers - Mr. Brightside - Hot Fuss",
  39: "Nirvana - Come as You Are - Nevermind",
  40: "Slipknot - Disasterpiece - Iowa",
  41: "Slipknot - Eyeless - Slipknot",
  42: "Limp Bizkit - Gold Cobra - Gold Cobra",
  43: "Celia Cruz - Guantanamera - La Bella Celia",
  44: "Green Day - Holiday - American Idiot",
  45: "Slipknot - Sulfur - All Hope Is Gone",
  46: "MC Hammer - U Can't Touch This - Please Hammer Don't Hurt 'Em",
  47: "Ill Niño - Unreal - Revolution Revolución",
  48: "Eve - Who's That Girl? - Scorpion",
  49: "Real to Real - I Like to Move It - I Like to Move It",
  50: "Rammstein - Keine Lust - Mutter",
};

module.exports = trackList;
